language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - wp

matrix:
  include:
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.6
      env: WP_VERSION=4.8
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=nightly
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      travis_retry composer require php-coveralls/php-coveralls
      travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
    fi

before_script:
  - mkdir -p build/logs

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs
    fi

after_success:
  - travis_retry php vendor/bin/php-coveralls
